### PR TITLE
feat: add function to parse Golang projects

### PR DESCRIPTION
**Pull request by ylsislove**
This commit adds a new function to parse Golang projects to the collection of crazy functions.

### CODE REVIEW

**Comment by binary-husky** [comment]
UI is a bit crowded，mind if I put it in the dropdown menu?

image

**Comment by ylsislove** [comment]
no problem



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 晚上7:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/chatgpt_academic] feat: add function to parse Golang projects (PR #239)





 
UI is a bit crowded，mind if I put it in the dropdown menu?

**Comment by binary-husky** [comment]
您好，有测试用例吗，我没用过golang语言

**Comment by ylsislove** [comment]
@binary-husky 我最近在学习SiYuan（https://github.com/siyuan-note/siyuan）这个框架，刚分析了下他们用go写的的kernel内核，分析的很棒。可以拿这一小部分代码作为测试用例（https://github.com/siyuan-note/siyuan/tree/master/kernel/cmd）
[cmd.zip](https://github.com/binary-husky/chatgpt_academic/files/11129368/cmd.zip)

**Pull request merged**
